import { Member } from './../types/member';

export const mockMembers: Member[] = [
  {
    uuid: "550e8400-e29b-41d4-a716-446655440001",
    name: "Johnny Rabelo",
    email: "johnny@toastytech.com",
    phone: "+55 13 99673-8213",
    photo: "/placeholder-user.jpg",
    position: "CTO & Full cycle Developer",
    bio: "Fundador da Toasty Tech, apaixonado por criar soluções inovadoras que transformam negócios. Especialista em desenvolvimento web e mobile com foco em aplicações escaláveis.",
    projects: ["1", "2", "4", "12", "11", "10", "9"],
    joinedAt: new Date("2023-01-15"),
    skills: ["React", "Next.js", "Node.js", "TypeScript", "Angular", "Microserviços", "Go", "Scrum", "Kanban", "Jira", "Gestão de Equipes", "Comunicação"],
    social: {
      linkedin: "https://linkedin.com/in/johnnyfr26",
      github: "https://github.com/johnnyfr26",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440002",
    name: "Samuel Varoli",
    email: "varoli@toastytech.com",
    phone: "+55 13 98849-1762",
    photo: "/placeholder-user.jpg",
    position: "CEO & Full Stack Developer",
    bio: "Fundador da Toasty Tech, criador de soluções digitais que transformam negócios por meio de experiências digitais marcantes. Desenvolvedor Web focado em todo tipo de usuário e negócio",
    projects: ["10", "11", "1"],
    joinedAt: new Date("2023-01-15"),
    skills: ["Node.js", "TypeScript", "Angular", "C++", "MySQL"],
    social: {
      linkedin: "https://linkedin.com/in/samuelvaroli",
      github: "https://github.com/VaroliDev",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440003",
    name: "Helena Neves",
    email: "helenanevesdesign@gmail.com",
    phone: "+55 13 97413-5094",
    photo: "/placeholder-user.jpg",
    position: "Designer & Front-end",
    bio: "Focada em design e tecnologia, crio interfaces e identidades visuais que unem estética e propósito. Trabalho com UI/UX, design gráfico e desenvolvimento web, entregando soluções digitais que encantam e funcionam.",
    projects: ["10", "12", "1"],
    joinedAt: new Date("2023-01-15"),
    skills: ["UI", "UX", "HTML", "CSS", "Figma", "Inkscape", "Design de Identidade Visual", "Design Gráfico", "Comunicação"],
    social: {
      linkedin: "https://www.linkedin.com/in/helenanevesdesign/",
      github: "https://github.com/devhelenaneves",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440004",
    name: "Alyson Gabriel",
    email: "alysongabriel07@gmail.com",
    phone: "+55 13 99705-4308",
    photo: "/placeholder-user.jpg",
    position: "FrontEnd Developer",
    bio: "Desenvolvedor Front, apaixonado por desafios complexos com soluções inovadoras. Especialista em desenvolvimento web com foco em animações e visuais.",
    projects: ["9", "10", "11", "12"],
    joinedAt: new Date("2023-01-15"),
    skills: [ "CSS", "Angular"],
    social: {
      github: "https://github.com/alygab",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440010",
    name: "Carlos Santos",
    email: "carlos@toastytech.com",
    phone: "+55 21 97654-3210",
    photo: "/placeholder-user.jpg",
    position: "Backend Developer",
    bio: "Especialista em arquitetura de sistemas e APIs escaláveis. Experiência em cloud computing e DevOps.",
    projects: ["2", "4", "8"],
    joinedAt: new Date("2023-05-10"),
    skills: ["Node.js", "Python", "PostgreSQL", "AWS", "Docker", "Kubernetes"],
    social: {
      linkedin: "https://linkedin.com/in/carlossantos",
      github: "https://github.com/carlossantos",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440009",
    name: "Juliana Costa",
    email: "juliana@toastytech.com",
    phone: "+55 31 96543-2109",
    photo: "/placeholder-user.jpg",
    position: "UI/UX Designer",
    bio: "Designer focada em criar experiências digitais memoráveis. Especialista em design systems e prototipagem.",
    projects: ["1", "4", "5", "7"],
    joinedAt: new Date("2023-07-01"),
    skills: ["Figma", "Adobe XD", "Sketch", "Design Systems", "User Research"],
    social: {
      linkedin: "https://linkedin.com/in/julianacosta",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440005",
    name: "Pedro Oliveira",
    email: "pedro@toastytech.com",
    phone: "+55 41 95432-1098",
    photo: "/placeholder-user.jpg",
    position: "Mobile Developer",
    bio: "Desenvolvedor mobile com expertise em React Native e Flutter. Apaixonado por criar apps performáticos.",
    projects: ["4"],
    joinedAt: new Date("2023-09-15"),
    skills: ["React Native", "Flutter", "iOS", "Android", "Firebase"],
    social: {
      linkedin: "https://linkedin.com/in/pedrooliveira",
      github: "https://github.com/pedrooliveira",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440006",
    name: "Mariana Ferreira",
    email: "mariana@toastytech.com",
    phone: "+55 51 94321-0987",
    photo: "/placeholder-user.jpg",
    position: "Project Manager",
    bio: "Gerente de projetos com foco em metodologias ágeis. Especialista em coordenar equipes e entregar resultados.",
    projects: ["2", "3", "8"],
    joinedAt: new Date("2023-11-01"),
    skills: ["Scrum", "Kanban", "Jira", "Gestão de Equipes", "Comunicação"],
    social: {
      linkedin: "https://linkedin.com/in/marianaferreira",
    },
  },
]

export function getMemberByUuid(uuid: string): Member | undefined {
  return mockMembers.find((member) => member.uuid === uuid)
}
