import type { Company, Project, RevenueReport } from "@/types/dashboard"

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechCorp Solutions",
    email: "contato@techcorp.com",
    phone: "+55 11 99999-9999",
    createdAt: new Date("2024-01-15"),
    projects: [],
  },
  {
    id: "2",
    name: "StartupXYZ",
    email: "hello@startupxyz.com",
    phone: "+55 21 88888-8888",
    createdAt: new Date("2024-02-20"),
    projects: [],
  },
  {
    id: "3",
    name: "E-commerce Plus",
    email: "suporte@ecommerceplus.com",
    phone: "+55 31 77777-7777",
    createdAt: new Date("2024-03-10"),
    projects: [],
  },
]

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Landing Page Corporativa",
    description: "Landing page moderna para captação de leads",
    category: "landing-page",
    status: "active",
    isInProgress: false,
    companyId: "1",
    monthlyRevenue: 2500,
    serverCost: 150,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "2",
    name: "Sistema CRM Personalizado",
    description: "CRM completo para gestão de clientes",
    category: "crm",
    status: "active",
    isInProgress: true,
    companyId: "1",
    monthlyRevenue: 8500,
    serverCost: 450,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-07-30"),
  },
  {
    id: "3",
    name: "App Mobile de Delivery",
    description: "Aplicativo mobile para delivery de comida",
    category: "mobile-app",
    status: "active",
    isInProgress: true,
    companyId: "2",
    monthlyRevenue: 12000,
    serverCost: 800,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-07-28"),
  },
  {
    id: "4",
    name: "Dashboard Analytics",
    description: "Dashboard para análise de dados de vendas",
    category: "dashboard",
    status: "inactive",
    isInProgress: false,
    companyId: "2",
    monthlyRevenue: 0,
    serverCost: 0,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-06-15"),
  },
  {
    id: "5",
    name: "E-commerce Completo",
    description: "Plataforma de e-commerce com pagamentos integrados",
    category: "e-commerce",
    status: "active",
    isInProgress: false,
    companyId: "3",
    monthlyRevenue: 15000,
    serverCost: 950,
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-05-10"),
  },
]

export const mockRevenueReports: RevenueReport[] = [
  {
    month: "Janeiro 2024",
    totalRevenue: 18000,
    totalCosts: 1200,
    profit: 16800,
    activeProjects: 3,
  },
  {
    month: "Fevereiro 2024",
    totalRevenue: 23000,
    totalCosts: 1400,
    profit: 21600,
    activeProjects: 4,
  },
  {
    month: "Março 2024",
    totalRevenue: 38000,
    totalCosts: 2400,
    profit: 35600,
    activeProjects: 5,
  },
  {
    month: "Abril 2024",
    totalRevenue: 38000,
    totalCosts: 2400,
    profit: 35600,
    activeProjects: 5,
  },
  {
    month: "Maio 2024",
    totalRevenue: 38000,
    totalCosts: 2400,
    profit: 35600,
    activeProjects: 4,
  },
  {
    month: "Junho 2024",
    totalRevenue: 23000,
    totalCosts: 1400,
    profit: 21600,
    activeProjects: 4,
  },
  {
    month: "Julho 2024",
    totalRevenue: 38000,
    totalCosts: 2400,
    profit: 35600,
    activeProjects: 4,
  },
]

export const categoryLabels = {
  "landing-page": "Landing Page",
  crm: "CRM",
  dashboard: "Dashboard",
  "mobile-app": "App Mobile",
  "e-commerce": "E-commerce",
  blog: "Blog",
  portfolio: "Portfólio",
  other: "Outros",
}
