import { Member } from './../types/member';

export const mockMembers: Member[] = [
  {
    uuid: "550e8400-e29b-41d4-a716-446655440001",
    name: "Johnny Rabelo",
    email: "johnny@toastytech.com.br",
    phone: "+55 13 99673-8213",
    photo: "/members/johnny.jpeg",
    position: "CTO & Full cycle Developer",
    bio: "Fundador da Toasty Tech, apaixonado por criar soluções inovadoras que transformam negócios. Especialista em desenvolvimento web e mobile com foco em aplicações escaláveis.",
    projects: ["1", "2", "4", "12", "11", "10", "9"],
    joinedAt: new Date("2023-01-15"),
    skills: ["React", "Next.js", "Node.js", "TypeScript", "Angular", "Microserviços", "Go", "Scrum", "Kanban", "Jira", "Gestão de Equipes", "Comunicação"],
    social: {
      linkedin: "https://linkedin.com/in/johnnyfr26",
      github: "https://github.com/johnnyfr26",
      custom: "https://johnny.toastytech.com.br",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440002",
    name: "Samuel Varoli",
    email: "scvaroli@outlook.com",
    phone: "+55 13 98849-1762",
    photo: "/placeholder-user.jpg",
    position: "CEO & Full Stack Developer",
    bio: "Fundador da Toasty Tech, criador de soluções digitais que transformam negócios por meio de experiências digitais marcantes. Desenvolvedor Web focado em todo tipo de usuário e negócio",
    projects: ["10", "11", "12"],
    joinedAt: new Date("2023-01-15"),
    skills: ["Node.js", "TypeScript", "Angular", "C++", "MySQL"],
    social: {
      linkedin: "https://linkedin.com/in/samuelvaroli",
      github: "https://github.com/VaroliDev",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440003",
    name: "Helena Neves",
    email: "helenanevesdesign@gmail.com",
    phone: "+55 13 97413-5094",
    photo: "/members/helena.jpeg",
    position: "Designer & Front-end",
    bio: "Focada em design e tecnologia, crio interfaces e identidades visuais que unem estética e propósito. Trabalho com UI/UX, design gráfico e desenvolvimento web, entregando soluções digitais que encantam e funcionam.",
    projects: ["10", "12", "1"],
    joinedAt: new Date("2023-01-15"),
    skills: ["UI", "UX", "HTML", "CSS", "Figma", "Inkscape", "Design de Identidade Visual", "Design Gráfico", "Comunicação"],
    social: {
      linkedin: "https://www.linkedin.com/in/helenanevesdesign/",
      github: "https://github.com/devhelenaneves",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440004",
    name: "Alyson Gabriel",
    email: "alysongabriel07@gmail.com",
    phone: "+55 13 99705-4308",
    photo: "/placeholder-user.jpg",
    position: "FrontEnd Developer",
    bio: "Desenvolvedor Front, apaixonado por desafios complexos com soluções inovadoras. Especialista em desenvolvimento web com foco em animações e visuais.",
    projects: ["9", "10", "11", "12"],
    joinedAt: new Date("2023-01-15"),
    skills: [ "CSS", "Angular"],
    social: {
      github: "https://github.com/alygab",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440005",
    name: "Pedro Baum",
    email: "baumpedro123@gmail.com",
    phone: "+55 13 98138-8649",
    photo: "/members/baum.jpeg",
    position: "Web Developer/Marketing",
    bio: "Co-fundador da ToastyTech especialista em comunicação e trabalho em equipe, sempre buscando manter a equipe unida e realizar um atendimento perfeito para os clientes.",
    projects: ["12", "11", "9"],
    joinedAt: new Date("2023-01-15"),
    skills: ["Comunicação", "Gerenciamento de grupo", "TypeScript", "Banco de Dados", "Atendimento ao cliente"],
    social: {
      linkedin: "https://www.linkedin.com/in/pedro-baum-06b642327",
      github: "https://github.com/baumpedro",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440006",
    name: "Julio Lisboa",
    email: "juliolisboabernardo@gmail.com",
    phone: "+55 13 98871-7489",
    photo: "/members/oar2.jpg",
    position: "Designer",
    bio: "Co-fundador da Toasty Tech, um cara que tem diversas ideias prontas para serem feitas. Melhorando no webdesign  e programação web.",
    projects: ["1", "2", "4"],
    joinedAt: new Date("2023-01-15"),
    skills: ["HTML", "CSS", "Javascript", "Canva", "Figma"],
    social: {
      github: "https://github.com/JLB-mazor",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440007",
    name: "Ana Beatriz",
    email: "abtoasty@gmail.com",
    phone: "+55 13 99723-7142",
    photo: "/members/ana.jpg",
    position: "Backend Developer",
    bio: "Desenvolvedora BackEnd com bastante afinidade à lógica de programação, interessada em entender e trabalhar com o funcionamento interno das coisas, o que realmente faz tudo acontecer por trás das aplicações.",
    projects: ["10", "12", "1"],
    joinedAt: new Date("2025-01-15"),
    skills: [ "Node.js", "TypeScript", "Angular", "JavaScript", "Adonis.js" ],
    social:{ 
      linkedin: "https://www.linkedin.com/in/analadeiradev?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      github: "https://github.com/anaabdev",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440008",
    name: "Eric Sandes",
    email: "ericsandes2007@gmail.com",
    phone: "+55 13 99618-4670",
    photo: "/members/eric.jpg",
    position: "Designer",
    bio: "Co-fundador da Toasty Tech, tentando fazer os programa ficarem bonito :). ",
    projects: ["11", "12", "9"],
    joinedAt: new Date("2023-02-15"),
    skills: ["Figma", "Photoshop", "ClipStudio", "Krita", "Ilustrator", "UX", "UI"],
    social: {
      instagram:
      "https://www.instagram.com/nao_eh_o_eric?igsh=dmdwZ2poOGdvNnRi"
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440009",
    name: "Natã Feitosa",
    email: "natafeitosa.toasty@gmail.com",
    phone: "+55 13 98809-3270",
    photo: "/placeholder-user.jpg",
    position: "Documentador e Analista De Documentação",
    bio: "Membro responsável pela documentação dos projetos da empresa. Se diverte enquanto trabalha, mantendo a sinergia com outros membros da equipe e o profissionalismo.",
    projects: [ "TecLibras" ],
    joinedAt: new Date("2023-01-15"),
    skills: [ "Comunicação" ],
    social: {
      github: "https://github.com/NataFeitosa",
    },
  },
  {
    uuid: "550e8400-e29b-41d4-a716-446655440010",
    name: "Miguel Santana Gonçalves",
    email: "miguelsg.toasty@gmail.com",
    phone: "+55 13 991090772",
    photo: "/placeholder-user.jpg",
    position: "CEO & Assistente de Comunicações",
    bio: "Técnico em Desenvolvimento de Sistemas especialista em comunicação, resolução de problemas e em diversos tipos de conhecimento relacionados a área da tecnologia e da sociedade como um todo.",
    projects: ["TecLibras"],
    joinedAt: new Date("2023-01-15"),
    skills: ["React", "Node.js", "TypeScript", "Angular", "C++"],
    social: {
      linkedin: "https://www.linkedin.com/in/miguel-santana-gonçalves-082754350?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    },
  },
]

export function getMemberByUuid(uuid: string): Member | undefined {
  return mockMembers.find((member) => member.uuid === uuid)
}
