import type { Company, Project, DashboardStats, MonthlyReport } from "@/types/dashboard"

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechCorp Solutions",
    email: "contato@techcorp.com",
    phone: "+55 11 99999-0001",
    website: "https://techcorp.com",
    createdAt: new Date("2024-01-15"),
    projects: [],
  },
  {
    id: "2",
    name: "StartupXYZ",
    email: "hello@startupxyz.com",
    phone: "+55 21 99999-0002",
    website: "https://startupxyz.com",
    createdAt: new Date("2024-02-20"),
    projects: [],
  },
  {
    id: "3",
    name: "E-commerce Plus",
    email: "vendas@ecommerceplus.com",
    phone: "+55 31 99999-0003",
    website: "https://ecommerceplus.com",
    createdAt: new Date("2024-03-10"),
    projects: [],
  },
  {
    id: "4",
    name: "HealthTech Innovations",
    email: "info@healthtech.com",
    phone: "+55 41 99999-0004",
    createdAt: new Date("2024-04-05"),
    projects: [],
  },
  {
    id: "5",
    name: "FinanceApp Co.",
    email: "contact@financeapp.com",
    phone: "+55 51 99999-0005",
    website: "https://financeapp.com",
    createdAt: new Date("2024-05-12"),
    projects: [],
  },
]

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Landing Page Corporativa",
    description: "Landing page moderna para captação de leads",
    category: "landing-page",
    status: "deployed",
    companyId: "1",
    monthlyRevenue: 2500,
    serverCost: 150,
    startDate: new Date("2024-01-20"),
    endDate: new Date("2024-02-15"),
    isActive: true,
  },
  {
    id: "2",
    name: "Sistema CRM Personalizado",
    description: "CRM completo para gestão de clientes e vendas",
    category: "crm",
    status: "development",
    companyId: "1",
    monthlyRevenue: 8500,
    serverCost: 450,
    startDate: new Date("2024-03-01"),
    isActive: true,
  },
  {
    id: "3",
    name: "Dashboard Analytics",
    description: "Dashboard para análise de dados de vendas",
    category: "dashboard",
    status: "testing",
    companyId: "2",
    monthlyRevenue: 4200,
    serverCost: 280,
    startDate: new Date("2024-02-25"),
    isActive: true,
  },
  {
    id: "4",
    name: "App Mobile iOS/Android",
    description: "Aplicativo mobile para delivery",
    category: "mobile-app",
    status: "development",
    companyId: "3",
    monthlyRevenue: 12000,
    serverCost: 800,
    startDate: new Date("2024-03-15"),
    isActive: true,
  },
  {
    id: "5",
    name: "E-commerce Completo",
    description: "Loja virtual com sistema de pagamentos",
    category: "e-commerce",
    status: "deployed",
    companyId: "3",
    monthlyRevenue: 6800,
    serverCost: 380,
    startDate: new Date("2024-01-10"),
    endDate: new Date("2024-03-20"),
    isActive: true,
  },
  {
    id: "6",
    name: "Blog Corporativo",
    description: "Blog com CMS personalizado",
    category: "blog",
    status: "maintenance",
    companyId: "4",
    monthlyRevenue: 1800,
    serverCost: 120,
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-28"),
    isActive: true,
  },
  {
    id: "7",
    name: "Portfolio Digital",
    description: "Site portfolio para arquiteta",
    category: "portfolio",
    status: "deployed",
    companyId: "5",
    monthlyRevenue: 1200,
    serverCost: 80,
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-20"),
    isActive: true,
  },
  {
    id: "8",
    name: "Sistema de Gestão Hospitalar",
    description: "Sistema completo para gestão hospitalar",
    category: "other",
    status: "planning",
    companyId: "4",
    monthlyRevenue: 15000,
    serverCost: 950,
    startDate: new Date("2024-06-01"),
    isActive: true,
  },
  {
    id: "9",
    name: "Finanz",
    description: "Sistema completo para gestão financeira",
    category: "other",
    status: "deployed",
    companyId: "5",
    monthlyRevenue: 8000,
    serverCost: 500,
    startDate: new Date("2024-06-01"),
    isActive: true,
  },
  {
    id: "10",
    name: "TechLibras",
    description: "Plataforma de aprendizado online de libras",
    category: "other",
    status: "planning",
    companyId: "1",
    monthlyRevenue: 2500,
    serverCost: 150,
    startDate: new Date("2024-01-20"),
    endDate: new Date("2024-02-15"),
    isActive: true,
  },
  {
    id: "11",
    name: "Animaldle",
    description: "Jogo de adivinhacao de animais",
    category: "other",
    status: "deployed",
    companyId: "3",
    monthlyRevenue: 12000,
    serverCost: 800,
    startDate: new Date("2024-03-15"),
    isActive: true,
  },
  {
    id: "12",
    name: "Piatia",
    description: "Loja virtual com sistema de pagamentos",
    category: "e-commerce",
    status: "deployed",
    companyId: "3",
    monthlyRevenue: 6800,
    serverCost: 380,
    startDate: new Date("2024-01-10"),
    endDate: new Date("2024-03-20"),
    isActive: true,
  },
]

mockCompanies.forEach((company) => {
  company.projects = mockProjects.filter((project) => project.companyId === company.id)
})

export const mockDashboardStats: DashboardStats = {
  totalCompanies: mockCompanies.length,
  totalProjects: mockProjects.length,
  activeProjects: mockProjects.filter((p) => p.isActive && ["development", "testing", "planning"].includes(p.status))
    .length,
  totalRevenue: mockProjects.reduce((sum, project) => sum + project.monthlyRevenue, 0),
  totalCosts: mockProjects.reduce((sum, project) => sum + project.serverCost, 0),
  totalProfit: mockProjects.reduce((sum, project) => sum + (project.monthlyRevenue - project.serverCost), 0),
}

export const mockMonthlyReports: MonthlyReport[] = [
  {
    month: "Janeiro 2024",
    revenue: 15200,
    costs: 1850,
    profit: 13350,
    newProjects: 2,
    completedProjects: 1,
  },
  {
    month: "Fevereiro 2024",
    revenue: 22800,
    costs: 2450,
    profit: 20350,
    newProjects: 3,
    completedProjects: 2,
  },
  {
    month: "Março 2024",
    revenue: 35600,
    costs: 3280,
    profit: 32320,
    newProjects: 2,
    completedProjects: 1,
  },
  {
    month: "Abril 2024",
    revenue: 41200,
    costs: 3850,
    profit: 37350,
    newProjects: 1,
    completedProjects: 2,
  },
  {
    month: "Maio 2024",
    revenue: 52000,
    costs: 4260,
    profit: 47740,
    newProjects: 1,
    completedProjects: 0,
  },
]

export const categoryLabels = {
  "landing-page": "Landing Page",
  crm: "CRM",
  dashboard: "Dashboard",
  "mobile-app": "App Mobile",
  "e-commerce": "E-commerce",
  blog: "Blog",
  portfolio: "Portfolio",
  other: "Outros",
}

export const statusLabels = {
  planning: "Planejamento",
  development: "Desenvolvimento",
  testing: "Testes",
  deployed: "Implantado",
  maintenance: "Manutenção",
  paused: "Pausado",
  cancelled: "Cancelado",
}

export const statusColors = {
  planning: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300",
  development: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300",
  testing: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300",
  deployed: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300",
  maintenance: "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-300",
  paused: "bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300",
  cancelled: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300",
}
